---
- name: COMMON| create random but idempotent password
  ansible.builtin.set_fact:
    common_random_password: "{{ lookup('ansible.builtin.password', '/dev/null', seed=inventory_hostname, chars=['ascii_lowercase', 'digits'], length=16) }}"

- name: COMMON | Import package installation tasks
  ansible.builtin.import_tasks: packages.yml
