---

- name: Disable APT recommends
  ansible.builtin.blockinfile:
    path: /etc/apt/apt.conf.d/02norecommends
    mode: 0644
    create: true
    block: |
      APT::Install-Recommends "false";
      APT::Install-Suggests "false";
      APT::Get::Install-Recommends "false";
      APT::Get::Install-Suggests "false";
      Acquire::Languages "none";
      Acquire::ForceIPv4 "true";

- name: Gather installed packages
  ansible.builtin.package_facts:
    manager: auto

- name: Docker repo and key
  block:
    - name: docker -> add Docker repo and apt key
      ansible.builtin.get_url:
        url: "https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower}}/gpg"
        dest: /etc/apt/trusted.gpg.d/docker.asc
        force: true

    - name: docker -> add Docker apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64  signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower}} {{ ansible_facts['distribution_release'] }} stable"
        state: present
        filename: docker
        update_cache: false
      when: ansible_facts['architecture'] == 'x86_64'

    - name: docker -> add Docker apt source
      ansible.builtin.apt_repository:
        repo: "deb [arch=arm64  signed-by=/etc/apt/trusted.gpg.d/docker.asc] https://download.docker.com/linux/{{ ansible_facts['distribution'] | lower}} {{ ansible_facts['distribution_release'] }} stable"
        state: present
        filename: docker
        update_cache: false
      when: ansible_facts['architecture'] == 'aarch64'

- name: Install APT packages
  ansible.builtin.apt:
    name: "{{ apt_packages }}"
    state: present
    autoclean: yes
    update_cache: yes
    install_recommends: no

- name: Install PIP packages
  ansible.builtin.pip:
    name: "{{pip_packages }}"
    state: present
