---
- name: restart security services
  service:
    name: "{{ item }}"
    state: restarted
  loop:
    - fail2ban
    - ufw

- name: reload fail2ban
  service:
    name: fail2ban
    state: reloaded

- name: reload ufw
  command: ufw reload
